name: 'spend_spent_spent'
version: '2.1.2+70'
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
description: Client for SpendSpentSpent self hosted expense tracker.
dependencies:
  after_layout: 1.2.0
  animations: 2.0.11
  auto_route: 8.3.0
  dynamic_color: 1.7.0
  easy_debounce: 2.0.3
  fl_chart: 0.69.0
  flutter:
    sdk: flutter
  flutter_animate: 4.5.0
  flutter_bloc: 8.1.6
  flutter_fadein: 2.0.0
  flutter_map: 7.0.2
  flutter_settings_ui: 3.0.1
  flutter_svg: '2.0.10+1'
  freezed_annotation: 2.4.4
  gap: 3.0.1
  http: 1.2.2
  intl: 0.19.0
  json_annotation: 4.9.0
  jwt_decoder: 2.0.1
  latlong2: 0.9.1
  location: 7.0.0
  package_info_plus: 8.0.2
  random_string: 2.3.1
  shared_preferences: 2.3.2
  tinycolor2: 3.0.1
dev_dependencies:
  analyzer: any
  auto_route_generator: 8.1.0
  build_runner: 2.4.12
  flutter_launcher_icons: '^0.13.1'
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: '^2.5.2'
  json_serializable: '^6.8.0'
  pubspec_dependency_sorter: 1.0.5
flutter_icons:
  android: false
  ios: true
  image_path_ios: images/ios.png
  image_path_android: images/android.png
flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: fonts/sss.ttf
