# This is a basic workflow to help you get started with Actions
name: Build Backend App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter analyze and build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #env:
    #  JAVA_VERSION: "11.0"
    #  FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      # Build web app
      - name: build web
        working-directory: src/main/app
        run: |
          git submodule init
          git submodule update
          ./submodules/flutter/bin/flutter doctor
          ./submodules/flutter/bin/flutter pub get
          ./submodules/flutter/bin/flutter doctor
          ./submodules/flutter/bin/flutter build web --release
          cp -R build/web ../resources/public
      # build backend

      - name: Extract tag name
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set application version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mvn versions:set -DnewVersion=${TAG_NAME}
          mvn versions:commit
      - name: Build Java app
        run: mvn clean install -Dspring.main.allow-circular-references=true
